const PortfolioData = () => {
  return [
    {
      title: "Caishen: The Cashiers App",
      description: "A portfolio app showcasing my skills and experience, built using Javascript, React, and Chakra UI.",
      cover: "https://picsum.photos/1920/1080",
      language: "Javascript",
      techStack: ["react", "javascript", "chakra-ui"],
      url: "https://github.com/MA-Ahmad/myPortfolio",
      live: "https://mahmad.me",
      stargazers_count: 0,
      forks_count: 22,
    },
    {
      title: "My Portfolio",
      description: "A personal portfolio app highlighting my skills and experience, developed with Javascript, React, and Chakra UI.",
      cover: "https://picsum.photos/1920/1081",
      language: "Javascript",
      techStack: ["react", "chakraUi"],
      url: "https://github.com/MA-Ahmad/portfolio",
      live: "https://ma-ahmad.github.io/portfolio",
      stargazers_count: 1,
      forks_count: 14,
    },
    {
      title: "Crea-te: The Web Blog",
      description: "A web blog crafted using Next.js, Chakra UI, and Javascript to showcase my work.",
      cover: "public/create.png",
      language: "Javascript",
      techStack: ["react", "chakra-ui"],
      url: "https://github.com/febrydjr/Crea-te",
      live: "https://crea-te.netlify.app",
      stargazers_count: 1,
      forks_count: 5,
    },
    {
      title: "Backend API of Web Blog",
      description: "A notebook app aiding in daily work by enabling note creation, built with Javascript, React, and Chakra UI.",
      cover: "https://picsum.photos/1920/1096",
      language: "Javascript",
      techStack: ["react", "javascript", "chakra-ui"],
      url: "https://github.com/MA-Ahmad/notebook",
      live: "https://ma-ahmad.github.io/notebook",
      stargazers_count: 0,
      forks_count: 8,
    },
    {
      title: "Simple Cart App",
      description: "A straightforward cart app designed to assist in managing daily tasks, created using Javascript and Chakra UI.",
      cover: "https://picsum.photos/1920/1086",
      language: "Javascript",
      techStack: ["chakra-ui", "react", "javascript"],
      url: "https://github.com/MA-Ahmad/notebook",
      live: "https://ma-ahmad.github.io/notebook",
      stargazers_count: 1,
      forks_count: 8,
    },
    {
      title: "Uku-Uku App: The Payroll Management",
      description: "An app for efficient payroll management, built with Javascript, React, and Chakra UI.",
      cover: "https://picsum.photos/1920/1376",
      language: "Javascript",
      techStack: ["react", "javascript", "chakra-ui"],
      url: "https://github.com/MA-Ahmad/notebook",
      live: "https://ma-ahmad.github.io/notebook",
      stargazers_count: 1,
      forks_count: 1,
    },
    {
      title: "Docs Generator",
      description: "A tool for generating documents, implemented in Python.",
      cover: "https://picsum.photos/1920/1176",
      language: "Python",
      techStack: ["python"],
      url: "https://github.com/MA-Ahmad/notebook",
      live: "https://ma-ahmad.github.io/notebook",
      stargazers_count: 1,
      forks_count: 1,
    },
  ];
}

module.exports = PortfolioData;
